# Generated by Django 3.2.16 on 2023-06-07 16:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Bunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_user', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunk.user')),
            ],
        ),
    ]
